apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-deployment
  labels:
    app: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
       containers:
        - image: themultitoolguy/techtrends:main-d9976c81-1631751313
          name: techtrends
          ports:
            - containerPort: 3111
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3111
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3111

